### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by ixdarchitects** [ixdarchitects/CloudDoc#1]
### Summary

_Brief summary here please :)_
_Bonus points for pictures!_

### Assets/Documentation

[](url)

### Tasks 

- [ ] This is a checkbox bullet list 
- [ ] This is a checkbox bullet list 
- [ ] This is a checkbox bullet list 
- [ ] This is a checkbox bullet list 
- [ ] This is a checkbox bullet list 

### Linked Issues

[](url)

### Primary Contacts

_Please include FULL names of external contacts!_
